name: wf-cd-production

on:
  push:
    branches:
      - "production"

jobs:
  build-production-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 1 # Fetch only the latest commit

      - name: Install Dependencies
        run: npm install

      - name: Build Website for Production
        run: |
          npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./"

      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"
          name: "build-artifact-production"

  deploy-production-job:
    needs: build-production-job
    environment: production-env
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Production Artifact
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "build-artifact-production"
          token: ${{ secrets.GITHUB_TOKEN }}
