name: wf-cd-staging

on:
  push:
    branches:
      - "release/**"

jobs:
  build-staging-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      # - name: InstallDependencies
      #   run: npm install

      - name: Build Website for Staging
        run: |
          npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./"

      - name: Upload Build Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./dist"
          name: "build-artifact-staging"

  deploy-staging-job:
    needs: build-staging-job
    environment: staging-env
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Staging Artifact
        uses: actions/deploy-pages@v4
        with:
          artifact_name: "build-artifact-staging"
          token: ${{github.token}}
