name: PR Validation

on:
  pull_request:
    branches:
      - develop

jobs:
  linting-job:
    name: Lint HTML and CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm install --save-dev htmlhint stylelint

      - name: Lint HTML and CSS
        run: |
          npx htmlhint "**/*.html"
          npx stylelint "**/*.css"